### ISSUE TITLE
Update major version of https-proxy-agent

### ISSUE THREAD

**Issue by tkandr** [scottgonzalez/node-browserstack#69]
Unfortunately, `https-proxy-agent@2` depends on `node-agent-base@4`, which [changes](https://github.com/TooTallNate/node-agent-base/blob/4.3.0/patch-core.js#L13) the functionality of core `https.request` and drops support of [https.request(url[, options][, callback])](https://nodejs.org/docs/latest-v12.x/api/https.html#https_https_request_url_options_callback) signature. Because of this, some other modules, which are using `https.request(url[, options][, callback])` are not working correctly (In my case, It's [got](https://github.com/sindresorhus/got)).

**Comment by nicolas-sainsburys** [comment]
This issue is impacting the usage of webdriverIO v6 with Browserstack tunnel.
The session request are sent by got library using a proxy over https. The service hostname get changed from hub-cloud.browserstack.com to 127.0.0.1 due to node-agent-base@4 override.
Forcing the npm package resolution to "https-proxy-agent": "^5.0.0" fix the issue.
Could you please upgrade your project to use a safe version of https-proxy-agent?
`
[0-2] 2020-09-15T22:41:35.109Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (.../node_modules/got/dist/source/core/index.js:940:25)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at ClientRequest.origin.emit (.../bdd/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
2020-09-15T22:41:35.110Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "https://<user>:<key>@hub-cloud.browserstack.com:443/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at startWebDriverSession (.../node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`
